14 파싱에 필요한 유틸함수
42minRT/miniRT pull request #18
Opened 2022-10-31 11:45 UTC by YeonSeong-Lee

2022-10-31 11:46 UTC, YeonSeong-Lee commented
<img width="733" alt="image" src="https://user-images.githubusercontent.com/62806979/199000676-6fe019bf-da43-4805-acc1-e44ef9977ac1.png">
이런식으로 필요한 곳에 parse_~~() 함수를 집어넣어서 사용하시면 됩니다.

2022-10-31 11:49 UTC, YeonSeong-Lee commented
parse_함수 동작확인

(0,0,1) 일때 
<img width="512" alt="Screen Shot 2022-10-31 at 8 48 15 PM" src="https://user-images.githubusercontent.com/62806979/199001023-f70c49e7-7a71-4301-8ba0-0cd9be53c528.png">

(40,0,1) 일때
<img width="512" alt="Screen Shot 2022-10-31 at 8 49 17 PM" src="https://user-images.githubusercontent.com/62806979/199001192-4d09e004-ea58-49a4-9a0e-2b7da368e7cf.png">

2022-10-31 15:42 UTC, jae-hwan-kim approved these changes
Good!

2022-10-31 15:42 UTC, jae-hwan-kim commented on include/utils.h
> +void		free_spited(char **target);
혹시 free_splited 인가요?

2022-10-31 15:42 UTC, jae-hwan-kim commented on src/utils/free_return.c
> +void	free_spited(char **target)
free_splited 인가요?!

2022-10-31 15:59 UTC, YeonSeong-Lee commented on src/utils/free_return.c
> +void	free_spited(char **target)
띠용..?! 맞습니다.

2022-11-01 02:42 UTC, sumnii commented on src/parse/is_valid/parse_elements.c
> +	last_element[ft_strlen(last_element) - 1] = '\0';;
```suggestion
	last_element[ft_strlen(last_element) - 1] = '\0';
```

2022-11-01 02:58 UTC, sumnii commented on src/utils/parse_elements.c
> +	xyz_vector = point3(x, y, z);
```suggestion
	xyz_vector = vec3(x, y, z);
```

같은 자료형이긴 하지만 벡터 유틸이 따로 있으니까 이왕이면?!

2022-11-01 02:58 UTC, sumnii commented on src/utils/parse_elements.c
> +	rgb_color = point3(r, g, b);
```suggestion
	rgb_color = color3(r, g, b);
```

이것도 같은 맥락으로!

2022-11-01 02:59 UTC, sumnii requested changes
suggestion이 있을 때는 [Request changes]로 제출하는게 맞을까요~?

2022-11-01 05:50 UTC, jhMin95 approved these changes
수고하셨습니다

2022-11-01 05:53 UTC, merged